export const FETCH_ARTICLE_LIST_INITIAL = "FETCH_ARTICLE_LIST_INITIAL";
export const FETCH_ARTICLE_LIST_LOADING = "FETCH_ARTICLE_LIST_LOADING";
export const FETCH_ARTICLE_LIST_SUCCESS = "FETCH_ARTICLE_LIST_SUCCESS";
export const FETCH_ARTICLE_LIST_FAILURE = "FETCH_ARTICLE_LIST_FAILURE";
