export const FETCH_ARTICLE_DETAIL_INITIAL = "FETCH_ARTICLE_DETAIL_INITIAL";
export const FETCH_ARTICLE_DETAIL_LOADING = "FETCH_ARTICLE_DETAIL_LOADING";
export const FETCH_ARTICLE_DETAIL_SUCCESS = "FETCH_ARTICLE_DETAIL_SUCCESS";
export const FETCH_ARTICLE_DETAIL_FAILURE = "FETCH_ARTICLE_DETAIL_FAILURE";
